harnessApiVersion: '1.0'
type: PIPELINE
description: to test non-prod workflow
pipelineStages:
- type: ENV_STATE
  name: Deploy-Non-Prod
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 1
  workflowName: Deploy-Non-Prod
